use_frameworks!

platform :ios, '9.0'

target 'HQGenericSDK_Example' do
  pod 'HQGenericSDK', :path => '../'

  target 'HQGenericSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
